"""init

Revision ID: 1160fec0af55
Revises: 
Create Date: 2025-06-22 01:00:04.124305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1160fec0af55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('manager_email', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['manager_email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=False),
    sa.Column('improvements', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('user')
    # ### end Alembic commands ###
